#!/usr/bin/env python3.6

import json

test = 'c:\\Users\\jbentes\\Desktop\\Test1.json'

def access1():
    color_dict = {}
    temp_dict = {}
    with open(test) as json_file:
        data = json.load(json_file)
        for group in data:
            original_color = group["color"]
            color_dict.setdefault(original_color, 0)
            color_dict[original_color] += 1
        temp_dict = data.copy()
        match_color(color_dict, temp_dict)

def match_color(color_dict, temp_dict):
    for color in color_dict:
        matched_color = []
        counter = (color_dict[color])
        auxcounter = counter
        counter1 = 0
        for group in temp_dict:
            if (group["color"] == color) and (counter1 < counter):
                matched_color.append(group)
                counter -= 1
        match_version(matched_color)
        #print_matched_colors(auxcounter, matched_color)

def match_version(matched_color):
    bingo = []
    for i in range(len(matched_color)):
        group = matched_color[i]
        min_ = int(group["min_version"] * 10)
        max_ = int(group["max_version"] * 10)
        for group1 in matched_color:
            if (len(matched_color) > 1):
                min1 = int(group1["min_version"] * 10)
                max1 = int(group1["max_version"] * 10)
                #print(min_, max_, " | " , min1, max1)
                if (intersect(min_, max_, min1, max1)==1) and (group1 not in bingo) and (group1 != group):
                    bingo.append(group1["name"])
            else:
                print("Unico elemento da cor!", group1["name"])

    if len(bingo)>0:
        auxcounter1= len(bingo)
        for el in set(bingo):
            auxcounter1 -= 1
            if auxcounter1 > 0:
                print(el, end=", ")
            else:
                print(", ", el, end=" ")
        print(" ")

        for p in matched_color:
            if group1["name"] not in bingo:
                print("Sem cruzar -> ", group1["name"])
                break

def intersect(mi_, ma_, mi1, ma1):
    for x in range(mi_, ma_):
        for y in range(mi1, ma1):
            if x == y:
                #print("Bingo!")
                return 1
    return 0

def print_matched_colors(auxcounter, matched_color):
    for group in matched_color:
        auxcounter -= 1
        if auxcounter > 0:
            print(group["name"], " | ", end=" ")
        else:
            print(group["name"], end=" ")
    print(" ")

def main():
    access1()

main()
