#!/usr/bin/env python3.6

word = "1ovo1"

def matching(word1):
    half = int(len(word1)/2)
    for i in range(half):
        if word1[i] != word1[-(i+1)]:
            return 0
    return 1

def main():
    print(matching(word))

main()
