#!/usr/bin/env python3.6

word = "1ovo1"

def matching(word1):
    check = 0
    fail = 0
    if len(word1) % 2 == 0:
        half = int(len(word1)/2)
    else:
        half = int((len(word1) - 1) / 2)
    for i in range(half):
        if word1[i] != word1[-(i+1)]:
            return 0
            exit
    return 1

def main():
    print(matching(word))

main()
