#!/usr/bin/env python3.6

passwords_array = ["1Dd@ovsdfs", "sdfasdf", "D5d@aaadfs"]

def minor(passwrd):
    for char in passwrd:
        if char.islower():
            return 1
    return 0

def major(passwrd):
    for char in passwrd:
        if char.isupper():
            return 1
    return 0

def digit(passwrd):
    for char in passwrd:
        if char.isdigit():
            return 1
    return 0

def spec_char(passwrd):
    Special_char = ("$", "#", "@")
    for char in passwrd:
        if char in Special_char:
            return 1
    return 0

def pass_size(passwrd):
    Min_size = 6
    Max_size = 12
    if (len(passwrd) >= Min_size) and (len(passwrd) <= Max_size):
        return 1
    else:
        return 0

def valid_pass(password1):
    valid = 0
    if minor(password1) == 1 and\
            major(password1) == 1 and\
            pass_size(password1) == 1 and\
            digit(password1) == 1 and\
            spec_char(password1) == 1:
        valid = password1
    return (valid)

def main():
    for password in passwords_array:
        if (valid_pass(password)) != 0:
            print(valid_pass(password))

main()
