#!/usr/bin/env python3.6

passwords = ["1Dd@ovsdfs", "sdfasdf", "5Dd@aaadfs"]

def valid_pass(password1):
    Special_char = ("$", "#", "@")
    Minor = 0
    Major = 0
    Number = 0
    Special = 0
    Min_size = 6
    Max_size = 12
    valid = 0
    if len(password1) < Max_size or len(password1) > Min_size:
        valid = 1
    for char in password1:
        if char.islower():
            Minor = 1
        if char.isupper():
            Major = 1
        if char.isdigit():
            Number = 1
        if char in Special_char:
            Special = 1
    if (Minor + Major + Number + Special) == 4 and valid == 1:
        valid = password1
    else:
        valid = 0
    return (valid)

def main():
    for password in passwords:
        if (valid_pass(password)) != 0:
            print(valid_pass(password))

main()
